CREATE TABLE TBL_USER(
    ID UUID NOT NULL PRIMARY KEY ,
    NAME VARCHAR(20) NOT NULL,
    LAST_NAME VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(20) NOT NULL,

    UNIQUE(EMAIL)
);